### ISSUE TITLE
midi output to built in speakers

### ISSUE THREAD

**Issue by zwhitchcox** [cwilso/MIDIDrums#5]
When I go to output, it only allows me to output to midi controllers...is there any way I can output directly to the speakers?

**Comment by zwhitchcox** [comment]
Ok, nevermind, it's outputting to the speakers now, but it's not reading my midi device..I mean, it's reading it, I can see in the console, but it's not playing anything

**Comment by zwhitchcox** [comment]
This is the output from the console: 

```
Note on - channel: 0 note: 57 velocity: 42
midi.js:15 Note on - channel: 0 note: 57 velocity: 41
```

**Comment by cwilso** [comment]
It's not supposed to.  See note in Readme - it's intended to be controlled by a Livid CNTRL-R.  I hard-coded it to use features of that controller.
